### ISSUE TITLE
TIMESTAMP values are showing up as NULL

### ISSUE THREAD

**Issue by garlibe** [outerbase/studio-desktop#12]
For some reason timestamp values are showing up as NULL for my PostgreSQL DB. For a second my heart dropped, but double checked back on DBeaver and the data is there, so don't know what happens on Outerbase.

**Comment by invisal** [comment]
Sorry about it. It is because Outerbase support for PostgreSQL is still very early and didn't support all of its data type. I will try to handle all data type.

Originally, Outerbase Studio was built for SQLite and it has great SQLite support. Our focus now is to make it work great on PostgreSQL and MySQL as well in coming month. Thanks for pointing out :)

**Comment by invisal** [comment]
It will be available on next release with the fix
